import type { DetectionPattern } from "../../types.js"

export const apiKeyPatterns: DetectionPattern[] = [
  {
    id: "openai-api-key",
    name: "OpenAI API Key",
    category: "api-keys",
    pattern: /sk-proj-[A-Za-z0-9_-]{20,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "openai-api-key-legacy",
    name: "OpenAI API Key (Legacy)",
    category: "api-keys",
    pattern: /sk-[A-Za-z0-9]{20,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "anthropic-api-key",
    name: "Anthropic API Key",
    category: "api-keys",
    pattern: /sk-ant-[A-Za-z0-9_-]{20,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "aws-access-key",
    name: "AWS Access Key ID",
    category: "api-keys",
    pattern: /AKIA[0-9A-Z]{16}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "aws-secret-key",
    name: "AWS Secret Access Key",
    category: "api-keys",
    pattern: /(?<=(?:aws_secret_access_key|AWS_SECRET_ACCESS_KEY|secret_access_key)\s*[=:]\s*)[A-Za-z0-9/+=]{40}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "gcp-api-key",
    name: "GCP API Key",
    category: "api-keys",
    pattern: /AIza[0-9A-Za-z_-]{35}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "github-pat",
    name: "GitHub Personal Access Token",
    category: "api-keys",
    pattern: /ghp_[A-Za-z0-9]{36,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "github-oauth",
    name: "GitHub OAuth Token",
    category: "api-keys",
    pattern: /gho_[A-Za-z0-9]{36,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "github-fine-grained-pat",
    name: "GitHub Fine-Grained PAT",
    category: "api-keys",
    pattern: /github_pat_[A-Za-z0-9_]{22,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "slack-token",
    name: "Slack Token",
    category: "api-keys",
    pattern: /xox[bpars]-[A-Za-z0-9-]{10,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "stripe-secret-key",
    name: "Stripe Secret Key",
    category: "api-keys",
    pattern: /sk_(live|test)_[A-Za-z0-9]{20,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "stripe-restricted-key",
    name: "Stripe Restricted Key",
    category: "api-keys",
    pattern: /rk_(live|test)_[A-Za-z0-9]{20,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "jwt-token",
    name: "JWT Token",
    category: "api-keys",
    pattern: /eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "generic-bearer-token",
    name: "Bearer Token",
    category: "api-keys",
    pattern: /(?<=Bearer\s+)[A-Za-z0-9_-]{20,}/g,
    redact: () => "[REDACTED]",
    confidence: "medium",
  },
  {
    id: "sendgrid-api-key",
    name: "SendGrid API Key",
    category: "api-keys",
    pattern: /SG\.[A-Za-z0-9_-]{22,}\.[A-Za-z0-9_-]{22,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "twilio-api-key",
    name: "Twilio API Key",
    category: "api-keys",
    pattern: /SK[0-9a-fA-F]{32}/g,
    redact: () => "[REDACTED]",
    confidence: "medium",
  },
  {
    id: "npm-token",
    name: "NPM Token",
    category: "api-keys",
    pattern: /npm_[A-Za-z0-9]{36,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "pypi-token",
    name: "PyPI Token",
    category: "api-keys",
    pattern: /pypi-[A-Za-z0-9_-]{50,}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
  {
    id: "discord-bot-token",
    name: "Discord Bot Token",
    category: "api-keys",
    pattern: /[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{27,}/g,
    redact: () => "[REDACTED]",
    confidence: "medium",
  },
  {
    id: "mailgun-api-key",
    name: "Mailgun API Key",
    category: "api-keys",
    pattern: /key-[0-9a-zA-Z]{32}/g,
    redact: () => "[REDACTED]",
    confidence: "high",
  },
]
