import type { SecurityGuardConfig } from "../types.js"

export const DEFAULT_CONFIG: SecurityGuardConfig = {
  categories: {
    "api-keys": true,
    credentials: true,
    "private-keys": true,
    docker: true,
    kubernetes: true,
    cloud: true,
    "pii-email": true,
    "pii-phone": true,
    "pii-ssn": true,
    "pii-credit-card": true,
    "pii-ip-address": false, // High false-positive rate
  },
  disabledPatterns: [],
  customPatterns: [],
  whitelistedPaths: [],
  blockedFilePaths: [
    "**/.env",
    "**/.env.*",
    "**/.env.local",
    "**/.env.production",
    "**/*.pem",
    "**/*.key",
    "**/*.p12",
    "**/*.pfx",
    "**/*.jks",
    "**/id_rsa",
    "**/id_ed25519",
    "**/id_ecdsa",
    "**/.aws/credentials",
    "**/.aws/config",
    "**/.docker/config.json",
    "**/.kube/config",
    "**/kubeconfig*",
    "**/values.secret.yaml",
    "**/values.secrets.yaml",
    "**/*.tfstate",
    "**/*.tfvars",
    "**/.vault-token",
    "**/.netrc",
    "**/.pgpass",
    "**/.my.cnf",
    "**/authorized_keys",
    "**/known_hosts",
  ],
  excludedTools: ["list"],
  blockedTools: [],
  sshOnlyMode: false,
  notifications: true,
  audit: {
    enabled: true,
    filePath: ".opencode/security-guard/audit.log",
    maxFileSize: 10 * 1024 * 1024, // 10MB
    maxFiles: 5,
    verbosity: "normal",
  },
  diagnosticLog: {
    enabled: false,
    filePath: ".opencode/security-guard/diagnostic.log",
    maxFileSize: 10 * 1024 * 1024, // 10MB
    maxFiles: 3,
  },
  env: {
    enabled: true,
    stripPatterns: [
      "*_SECRET",
      "*_SECRET_*",
      "*_TOKEN",
      "*_TOKEN_*",
      "*_PASSWORD",
      "*_PASSWORD_*",
      "*_KEY",
      "*_API_KEY",
      "*_API_KEY_*",
      "*_PRIVATE_KEY",
      "DOCKER_AUTH_*",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_SESSION_TOKEN",
      "GITHUB_TOKEN",
      "VAULT_TOKEN",
      "PULUMI_CONFIG_PASSPHRASE",
      "HEROKU_API_KEY",
      "VERCEL_TOKEN",
      "CF_API_TOKEN",
      "CF_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "DATABASE_URL",
      "REDIS_URL",
      "MONGODB_URI",
    ],
  },
  indirectExecution: {
    enabled: true,
    scriptExtensions: [
      ".sh", ".bash", ".zsh", ".ksh", ".csh", ".fish",
      ".py", ".pyw", ".pl", ".pm", ".rb", ".js", ".mjs", ".cjs", ".ts", ".mts",
      ".php", ".lua", ".r", ".R", ".ps1", ".bat", ".cmd", ".awk", ".tcl", ".expect",
    ],
    systemPaths: [
      "/usr/bin/", "/usr/local/bin/", "/bin/", "/sbin/",
      "/usr/sbin/", "/usr/local/sbin/", "/opt/", "/snap/bin/", "/nix/store/",
    ],
    maxContentSize: 65536, // 64KB — limited by LLM context window
    blockBinaries: true,
    interpreters: [
      "bash", "sh", "zsh", "dash", "ksh", "csh", "fish",
      "python", "python3", "python2", "node", "deno", "bun",
      "perl", "ruby", "php", "lua", "Rscript", "pwsh",
      "awk", "gawk", "mawk", "tclsh", "expect",
    ],
    systemPrompt: "",
    promptTemplate: "",
  },
  llm: {
    enabled: false,
    debug: true,
    contextAccumulation: false,
    contextDetectionsOnly: true,
    maxContextPairs: 5,
    maxContextChars: 16000,
    providers: [],
    safetyEvaluator: {
      enabled: true,
      providers: [],
      baseUrl: "",
      model: "",
      apiKey: "",
      timeout: 0,
      temperature: 0,
      headers: {},
      healthCheckPath: "",
      completionsPath: "",
      tools: ["bash", "write", "edit", "read", "webfetch"],
      blockThreshold: "high",
      warnThreshold: "medium",
      bypassedCommands: [
        "git status",
        "git log",
        "git diff",
        "git branch",
        "git show",
        "ls",
        "pwd",
        "echo",
        "cat",
        "head",
        "tail",
        "wc",
        "date",
        "whoami",
      ],
      allowedOperations: [],
      operationalProfiles: {},
      systemPrompt: "",
      promptTemplate: "",
      actionMode: "block",
    },
    outputTriage: {
      enabled: true,
      providers: [],
      baseUrl: "",
      model: "",
      apiKey: "",
      timeout: 0,
      temperature: 0,
      headers: {},
      healthCheckPath: "",
      completionsPath: "",
      systemPrompt: "",
      promptTemplate: "",
    },
    outputTextTriage: {
      enabled: true,
      providers: [],
      baseUrl: "",
      model: "",
      apiKey: "",
      timeout: 0,
      temperature: 0,
      headers: {},
      healthCheckPath: "",
      completionsPath: "",
      systemPrompt: "",
      promptTemplate: "",
    },
    outputSanitizer: {
      enabled: true,
      providers: [],
      baseUrl: "",
      model: "",
      apiKey: "",
      timeout: 0,
      temperature: 0,
      headers: {},
      healthCheckPath: "",
      completionsPath: "",
      tools: ["read", "bash", "grep"],
      bypassedCommands: [
        // ── Container runtime (listings & metrics only — NOT logs/inspect/exec) ──
        "docker ps",
        "docker images",
        "docker stats",
        "docker top",
        "docker port",
        "docker info",
        "docker version",
        "docker system df",
        "docker container ls",
        "docker image ls",
        "docker compose ps",
        "docker compose ls",
        "docker compose top",
        "docker network ls",
        "docker volume ls",
        "docker-compose ps",
        "docker-compose top",
        "podman ps",
        "podman images",
        "podman stats",
        "podman top",
        "podman port",
        "podman info",
        "podman version",
        "podman pod ps",
        "podman pod list",
        "podman container ls",
        "podman image ls",
        "podman network ls",
        "podman volume ls",
        "crictl ps",
        "crictl images",
        "crictl pods",
        "crictl stats",
        // ── Kubernetes (structural/metrics only — NOT get/describe/logs) ──
        "kubectl top",
        "kubectl version",
        "kubectl cluster-info",
        "kubectl api-resources",
        "kubectl api-versions",
        // ── Helm (listings only — NOT get values/status with notes) ──
        "helm list",
        "helm version",
        "helm repo list",
        "helm search",
        // ── Service management ──
        "systemctl status",
        "systemctl list-units",
        "systemctl list-timers",
        "systemctl list-sockets",
        "systemctl list-dependencies",
        "systemctl is-active",
        "systemctl is-enabled",
        "service --status-all",
        // ── System monitoring & performance ──
        "uptime",
        "free",
        "df",
        "top -bn1",
        "vmstat",
        "iostat",
        "mpstat",
        "sar",
        "nproc",
        "getconf",
        "ulimit",
        "timedatectl",
        "localectl",
        "hostnamectl",
        "dmesg",
        "w",
        "who",
        "last",
        // ── Process management ──
        "ps aux",
        "ps -ef",
        "pgrep",
        "pidof",
        // ── Networking (topology & status — NOT data-fetching like curl/wget) ──
        "lsof -i",
        "ss -tlnp",
        "ss -an",
        "ss -tunlp",
        "netstat -an",
        "netstat -tlnp",
        "ping",
        "traceroute",
        "tracepath",
        "mtr",
        "dig",
        "nslookup",
        "host",
        "whois",
        "ip addr",
        "ip route",
        "ip link",
        "ip neigh",
        "ip -s link",
        "ifconfig",
        "route",
        "arp",
        "ethtool",
        "brctl show",
        "bridge link",
        "resolvectl status",
        // ── Firewall & network security ──
        "ufw status",
        "ufw app list",
        "ufw show",
        "iptables -L",
        "iptables -S",
        "iptables -nvL",
        "ip6tables -L",
        "ip6tables -S",
        "nft list",
        "firewall-cmd --list-all",
        "firewall-cmd --list-services",
        "firewall-cmd --list-ports",
        "firewall-cmd --get-active-zones",
        "firewall-cmd --state",
        // ── CrowdSec (status & listings — NOT config show) ──
        "cscli decisions list",
        "cscli alerts list",
        "cscli bouncers list",
        "cscli machines list",
        "cscli metrics",
        "cscli hub list",
        "cscli collections list",
        "cscli parsers list",
        "cscli scenarios list",
        "cscli postoverflows list",
        "cscli lapi status",
        "cscli capi status",
        "cscli explain",
        // ── Fail2ban ──
        "fail2ban-client status",
        // ── SELinux & AppArmor ──
        "sestatus",
        "getenforce",
        "aa-status",
        "apparmor_status",
        // ── TLS / Certificates ──
        "certbot certificates",
        "certbot renew",
        // ── Hardware & system info ──
        "lscpu",
        "lsmem",
        "lsblk",
        "lspci",
        "lsusb",
        "lsmod",
        "lsns",
        "lsipc",
        "lslogins",
        // ── Disk & storage (layout only — NOT mount/findmnt which can show CIFS passwords) ──
        "fdisk -l",
        "parted -l",
        "blkid",
        "zpool status",
        "zpool list",
        "zfs list",
        "lvs",
        "vgs",
        "pvs",
        "mdadm --detail",
        "btrfs filesystem show",
        "smartctl",
        // ── Git (structural info — regex still catches secrets in diffs) ──
        "git status",
        "git log",
        "git diff",
        "git branch",
        "git show",
        "git remote",
        "git stash list",
        "git tag",
        "git shortlog",
        "git rev-parse",
        "git describe",
        "git reflog",
        "git ls-files",
        "git ls-tree",
        "git count-objects",
        "git fsck",
        // ── Filesystem info (metadata only — NOT file-content readers like cat/head/tail) ──
        "ls",
        "pwd",
        "wc",
        "date",
        "whoami",
        "uname",
        "hostname",
        "id",
        "groups",
        "du",
        "stat",
        "file",
        "which",
        "type",
        "tree",
        "realpath",
        "basename",
        "dirname",
        "md5sum",
        "sha256sum",
        "sha1sum",
        // ── Web server / reverse proxy (syntax checks & version — NOT -T config dump) ──
        "nginx -t",
        "nginx -v",
        "nginx -V",
        "apache2ctl -t",
        "apache2ctl -S",
        "apache2ctl -M",
        "httpd -t",
        "httpd -S",
        "httpd -M",
        "caddy version",
        "caddy validate",
        "haproxy -c",
        // ── Package managers (listings & updates — output is package names/versions, no secrets) ──
        "apt list",
        "apt update",
        "apt upgrade",
        "apt full-upgrade",
        "apt dist-upgrade",
        "apt install",
        "apt remove",
        "apt autoremove",
        "apt search",
        "apt show",
        "dpkg -l",
        "dpkg --list",
        "rpm -qa",
        "yum list",
        "yum update",
        "yum upgrade",
        "dnf list",
        "dnf update",
        "dnf upgrade",
        "pacman -Q",
        "pacman -Syu",
        "apk list",
        "apk update",
        "apk upgrade",
        "brew list",
        "brew update",
        "brew upgrade",
        "brew outdated",
        "snap list",
        "snap refresh",
        "flatpak list",
        "flatpak update",
        "pip list",
        "pip freeze",
        "pip install",
        "npm list",
        "npm install",
        "npm update",
        "gem list",
        // ── Build / test / lint (output is compile errors, test results, lint warnings) ──
        "make",
        "npm run build",
        "npm test",
        "npx tsc",
        "npx eslint",
        "npx prettier --check",
        "bun test",
        "bun run build",
        "cargo build",
        "cargo test",
        "cargo clippy",
        "cargo check",
        "go build",
        "go test",
        "go vet",
        "gradle build",
        "gradle test",
        "gradlew build",
        "gradlew test",
        "./gradlew build",
        "./gradlew test",
        "mvn compile",
        "mvn test",
        "mvn verify",
        "dotnet build",
        "dotnet test",
        "python -m pytest",
        "pytest",
        "jest",
        "vitest",
        "pnpm test",
        "pnpm run build",
        "yarn test",
        "yarn build",
        // ── IaC (safe structural subset — NOT plan/apply which expose values) ──
        "terraform version",
        "terraform providers",
        "terraform workspace list",
        "terraform fmt",
        "terraform validate",
        "terraform state list",
        // ── Virtualization ──
        "virsh list",
        "virsh dominfo",
        "virsh nodeinfo",
      ],
      skipWhenRegexClean: false,
      maxOutputSize: 0,
      systemPrompt: "",
      promptTemplate: "",
      actionMode: "redact",
    },
  },
}
